### ISSUE TITLE
Bug Report: Components for refined resources not appearing

### ISSUE THREAD

**Issue by spellberry** [Icaruk/albion-profit#1]
## Description
The components appear without issue when using the calculator, choosing a craftable item (armor, etc.), and clicking the hammer icon. But whenever I do the same thing for refined resources (bars, planks, etc.), the components don't show. Below is a video, showcasing the problem.

https://github.com/user-attachments/assets/b04c3f0d-be4f-40b1-a523-1ba69ea402cb

**Comment by Icaruk** [comment]
Hi @spellberry 
Thanks for submitting this issue!

This tool uses the Albion Online API to fetch the required items, unfortunately  and they have missing fields on some items.
Here are some examples (check `craftingRequirements` field):

- Bag
https://gameinfo.albiononline.com/api/gameinfo/items/T3_BAG/data
![image](https://github.com/user-attachments/assets/700acf50-e043-475a-9b93-1a06a3f2ffed)

- Bronze bar
https://gameinfo.albiononline.com/api/gameinfo/items/T3_METALBAR/data
![image](https://github.com/user-attachments/assets/a596a16d-4588-4028-aef8-4f9f7d1739dc)

I added notifications to give some feedback to the user.
At the moment I haven't found a better solution.

![image](https://github.com/user-attachments/assets/e0798512-124b-4a3d-808c-b089df3c0b6e)

**Comment by spellberry** [comment]
Ah, I see. That's unfortunate. Still, adding the ingredients manually is not such a big deal. Also, while I am writing here, I wanted to ask what the "Mod%" field is for. And are you planning to add a field for the tax cost for the refine station a player uses? I think these are big QoL features that can make this calculator even better.

**Comment by Icaruk** [comment]
> Ah, I see. That's unfortunate. Still, adding the ingredients manually is not such a big deal. Also, while I am writing here, I wanted to ask what the "Mod%" field is for. And are you planning to add a field for the tax cost for the refine station a player uses? I think these are big QoL features that can make this calculator even better.

- Mod % field (modifier % field)
Example: Lymhurst has bonus for fiber production, you can check the value here  
![image](https://github.com/user-attachments/assets/366980fe-f9fb-44e9-a0c2-cd36168fa442)

Then you can add the value and calculation will be done with the bonus:
![image](https://github.com/user-attachments/assets/e6e8bb43-d248-42a0-9da2-65debacca4c2)

`100 * 1.37 = 137`



- Tax cost
You can add an empty component, set custom price, and the calculation will be done.
![image](https://github.com/user-attachments/assets/4266f713-f306-406a-8f62-3812062d3522)

**Comment by Icaruk** [comment]
@spellberry I added a tooltip for "Mod %"

![image](https://github.com/user-attachments/assets/7704fb71-193d-42c1-a9b6-b5eff55c6b9b)

**Comment by Icaruk** [comment]
@spellberry Good news!

I found a pattern to find required items for each refined resource (except enchanted ones) let me know if it works for you!
